name: Build asset on macOS

on: [push]

jobs:
  build_asset_mac:
    name: Build asset on macOS
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependency
        run: |
          brew install coreutils automake

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run Buildscript
        run: |
          bundle exec rake update_library_macos

