name: Build asset on Windows

on: [push]

jobs:
  build_asset_windows:
    name: Build asset on Windows
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1.82.0
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Remove Name Conflict
        shell: pwsh
        run: mv C:\msys64\usr\bin\link.exe C:\msys64\usr\bin\msys-link.exe

      - name: Run Buildscript
        run: bundle exec rake prepare_library_windows

      - name: Install Dependency x86_64
        uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x86_64
      - name: Run Buildscript
        run: bundle exec rake update_library_windows_x64

      - name: Install Dependency x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x86
      - name: Run Buildscript
        run: bundle exec rake update_library_windows_x86

      - name: Install Dependency x86_arm64
        uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x86_arm64
      - name: Run Buildscript
        run: bundle exec rake update_library_windows_arm64

