name: Build asset on Linux

on: [push]

jobs:
  build_asset_linux:
    name: Build asset on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1.82.0
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run Buildscript
        run: |
          bundle exec rake update_library_linux

